/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.1.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.delivery.adapters.in.http.api;

import com.delivery.adapters.in.http.model.Courier;
import com.delivery.adapters.in.http.model.Error;
import com.delivery.adapters.in.http.model.NewCourier;
import com.delivery.adapters.in.http.model.Order;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import jakarta.validation.Valid;

import java.util.List;

import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-12-18T11:18:35.125812800+02:00[Europe/Kaliningrad]")
@Validated
@Tag(name = "api", description = "the api API")
public interface ApiApi {

    /**
     * POST /api/v1/couriers : Добавить курьера
     * Позволяет добавить курьера
     *
     * @param newCourier Курьер (optional)
     * @return Успешный ответ (status code 201)
     *         or Ошибка валидации (status code 400)
     *         or Ошибка выполнения бизнес логики (status code 409)
     *         or Ошибка (status code 200)
     */
    @Operation(
        operationId = "createCourier",
        summary = "Добавить курьера",
        description = "Позволяет добавить курьера",
        responses = {
            @ApiResponse(responseCode = "201", description = "Успешный ответ"),
            @ApiResponse(responseCode = "400", description = "Ошибка валидации", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "409", description = "Ошибка выполнения бизнес логики", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "default", description = "Ошибка", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/v1/couriers",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<Void> createCourier(
        @Parameter(name = "NewCourier", description = "Курьер") @Valid @RequestBody(required = false) NewCourier newCourier
    );


    /**
     * POST /api/v1/orders : Создать заказ
     * Позволяет создать заказ с целью тестирования
     *
     * @return Успешный ответ (status code 201)
     *         or Ошибка (status code 200)
     */
    @Operation(
        operationId = "createOrder",
        summary = "Создать заказ",
        description = "Позволяет создать заказ с целью тестирования",
        responses = {
            @ApiResponse(responseCode = "201", description = "Успешный ответ"),
            @ApiResponse(responseCode = "default", description = "Ошибка", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/v1/orders",
        produces = { "application/json" }
    )
    
    ResponseEntity<Void> createOrder(
        
    );


    /**
     * GET /api/v1/couriers : Получить всех курьеров
     * Позволяет получить всех курьеров
     *
     * @return Успешный ответ (status code 200)
     *         or Ошибка (status code 200)
     */
    @Operation(
        operationId = "getCouriers",
        summary = "Получить всех курьеров",
        description = "Позволяет получить всех курьеров",
        responses = {
            @ApiResponse(responseCode = "200", description = "Успешный ответ", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Courier.class)))
            }),
            @ApiResponse(responseCode = "default", description = "Ошибка", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/v1/couriers",
        produces = { "application/json" }
    )
    
    ResponseEntity<List<Courier>> getCouriers(
        
    );


    /**
     * GET /api/v1/orders/active : Получить все незавершенные заказы
     * Позволяет получить все незавершенные заказы
     *
     * @return Успешный ответ (status code 200)
     *         or Ошибка (status code 200)
     */
    @Operation(
        operationId = "getOrders",
        summary = "Получить все незавершенные заказы",
        description = "Позволяет получить все незавершенные заказы",
        responses = {
            @ApiResponse(responseCode = "200", description = "Успешный ответ", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Order.class)))
            }),
            @ApiResponse(responseCode = "default", description = "Ошибка", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/v1/orders/active",
        produces = { "application/json" }
    )
    
    ResponseEntity<List<Order>> getOrders(
        
    );

}
